### PR TITLE
Remove wasabi

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gus4rs** [comment]
+1
Wasabi is being listed but no disclaimer is in place to the fact they work with chain analysis and surveillance  companies to censor UTXOs that want to participate in the coinjoins. They effectively use their profits to help fund anti-freedom and surveillance companies and are a net negative for privacy in the space

**Comment by SamouraiDev** [comment]
ACK

**Comment by BitcoinQnA** [comment]
Thanks

**Comment by DanielPX1** [comment]
based

**Pull request merged**
